-- Script SQL para inserir dados de teste com diferentes meses
-- Execute este script na console H2 para testar o gráfico de economia mensal
-- Acesse: http://localhost:8080/h2-console
-- JDBC URL: jdbc:h2:file:~/realconsultdb
-- User: SA
-- Password: (deixe vazio)

-- IMPORTANTE: Substitua os IDs abaixo pelos IDs reais do seu banco
-- Para verificar os IDs, execute:
-- SELECT * FROM AUDITORIA;
-- SELECT * FROM FUNCIONARIO;

-- Exemplo de como criar dados de teste para diferentes meses
-- Ajuste os valores conforme necessário

-- Supondo que você tenha uma auditoria com ID = 1 e alguns funcionários

-- Primeiro, vamos verificar se há funcionários existentes
-- SELECT * FROM FUNCIONARIO WHERE AUDITORIA_ID = 1 LIMIT 5;

-- Copiar funcionários existentes para diferentes meses (exemplo)
-- Você precisa ajustar os IDs e valores conforme seus dados reais

-- Exemplo: Inserir dados para Janeiro/2025 (ajuste os valores)
INSERT INTO FUNCIONARIO (
    MATRICULA, AUDITORIA_ID, NOME_FUNCIONARIO, UNIDADE, SITUACAO,
    CUSTO_ATUAL, CUSTO_PROPOSTO, VALOR_CUSTO_IMPLANTADO,
    ECONOMIA_VALOR, ECONOMIA_PERCENTUAL, TIPO_DIA, DIAS_MES,
    VALOR_DIARIO, ECONOMIA_IMPLANTADA,
    TARIFA_LINHAUM_IDA, TARIFA_LINHADOIS_IDA, TARIFA_LINHATRES_IDA, TARIFA_LINHAQUATRO_IDA,
    TARIFA_LINHAUM_VOLTA, TARIFA_LINHADOIS_VOLTA, TARIFA_LINHATRES_VOLTA, TARIFA_LINHAQUATRO_VOLTA,
    OPERADORA_IDA, OPERADORA_VOLTA,
    MES_REFERENCIA, ANO_REFERENCIA
)
SELECT 
    MATRICULA, 
    AUDITORIA_ID,
    NOME_FUNCIONARIO,
    UNIDADE,
    SITUACAO,
    CUSTO_ATUAL * 1.05,  -- 5% a mais para variação
    CUSTO_PROPOSTO,
    VALOR_CUSTO_IMPLANTADO * 1.03,  -- 3% a mais
    ECONOMIA_VALOR * 0.95,  -- Economia um pouco menor
    ECONOMIA_PERCENTUAL,
    TIPO_DIA,
    DIAS_MES,
    VALOR_DIARIO,
    ECONOMIA_IMPLANTADA * 0.97,
    TARIFA_LINHAUM_IDA,
    TARIFA_LINHADOIS_IDA,
    TARIFA_LINHATRES_IDA,
    TARIFA_LINHAQUATRO_IDA,
    TARIFA_LINHAUM_VOLTA,
    TARIFA_LINHADOIS_VOLTA,
    TARIFA_LINHATRES_VOLTA,
    TARIFA_LINHAQUATRO_VOLTA,
    OPERADORA_IDA,
    OPERADORA_VOLTA,
    1,  -- Janeiro
    2025  -- Ano 2025
FROM FUNCIONARIO 
WHERE AUDITORIA_ID = 1 
  AND (MES_REFERENCIA IS NULL OR MES_REFERENCIA != 1)  -- Evitar duplicatas
LIMIT 10;

-- Exemplo: Inserir dados para Fevereiro/2025
INSERT INTO FUNCIONARIO (
    MATRICULA, AUDITORIA_ID, NOME_FUNCIONARIO, UNIDADE, SITUACAO,
    CUSTO_ATUAL, CUSTO_PROPOSTO, VALOR_CUSTO_IMPLANTADO,
    ECONOMIA_VALOR, ECONOMIA_PERCENTUAL, TIPO_DIA, DIAS_MES,
    VALOR_DIARIO, ECONOMIA_IMPLANTADA,
    TARIFA_LINHAUM_IDA, TARIFA_LINHADOIS_IDA, TARIFA_LINHATRES_IDA, TARIFA_LINHAQUATRO_IDA,
    TARIFA_LINHAUM_VOLTA, TARIFA_LINHADOIS_VOLTA, TARIFA_LINHATRES_VOLTA, TARIFA_LINHAQUATRO_VOLTA,
    OPERADORA_IDA, OPERADORA_VOLTA,
    MES_REFERENCIA, ANO_REFERENCIA
)
SELECT 
    MATRICULA,
    AUDITORIA_ID,
    NOME_FUNCIONARIO,
    UNIDADE,
    SITUACAO,
    CUSTO_ATUAL * 1.08,  -- 8% a mais
    CUSTO_PROPOSTO,
    VALOR_CUSTO_IMPLANTADO * 1.05,  -- 5% a mais
    ECONOMIA_VALOR * 0.92,
    ECONOMIA_PERCENTUAL,
    TIPO_DIA,
    DIAS_MES,
    VALOR_DIARIO,
    ECONOMIA_IMPLANTADA * 0.95,
    TARIFA_LINHAUM_IDA,
    TARIFA_LINHADOIS_IDA,
    TARIFA_LINHATRES_IDA,
    TARIFA_LINHAQUATRO_IDA,
    TARIFA_LINHAUM_VOLTA,
    TARIFA_LINHADOIS_VOLTA,
    TARIFA_LINHATRES_VOLTA,
    TARIFA_LINHAQUATRO_VOLTA,
    OPERADORA_IDA,
    OPERADORA_VOLTA,
    2,  -- Fevereiro
    2025
FROM FUNCIONARIO 
WHERE AUDITORIA_ID = 1 
  AND (MES_REFERENCIA IS NULL OR MES_REFERENCIA != 2)
LIMIT 10;

-- Exemplo: Inserir dados para Março/2025
INSERT INTO FUNCIONARIO (
    MATRICULA, AUDITORIA_ID, NOME_FUNCIONARIO, UNIDADE, SITUACAO,
    CUSTO_ATUAL, CUSTO_PROPOSTO, VALOR_CUSTO_IMPLANTADO,
    ECONOMIA_VALOR, ECONOMIA_PERCENTUAL, TIPO_DIA, DIAS_MES,
    VALOR_DIARIO, ECONOMIA_IMPLANTADA,
    TARIFA_LINHAUM_IDA, TARIFA_LINHADOIS_IDA, TARIFA_LINHATRES_IDA, TARIFA_LINHAQUATRO_IDA,
    TARIFA_LINHAUM_VOLTA, TARIFA_LINHADOIS_VOLTA, TARIFA_LINHATRES_VOLTA, TARIFA_LINHAQUATRO_VOLTA,
    OPERADORA_IDA, OPERADORA_VOLTA,
    MES_REFERENCIA, ANO_REFERENCIA
)
SELECT 
    MATRICULA,
    AUDITORIA_ID,
    NOME_FUNCIONARIO,
    UNIDADE,
    SITUACAO,
    CUSTO_ATUAL * 1.10,  -- 10% a mais
    CUSTO_PROPOSTO,
    VALOR_CUSTO_IMPLANTADO * 1.07,  -- 7% a mais
    ECONOMIA_VALOR * 0.90,
    ECONOMIA_PERCENTUAL,
    TIPO_DIA,
    DIAS_MES,
    VALOR_DIARIO,
    ECONOMIA_IMPLANTADA * 0.93,
    TARIFA_LINHAUM_IDA,
    TARIFA_LINHADOIS_IDA,
    TARIFA_LINHATRES_IDA,
    TARIFA_LINHAQUATRO_IDA,
    TARIFA_LINHAUM_VOLTA,
    TARIFA_LINHADOIS_VOLTA,
    TARIFA_LINHATRES_VOLTA,
    TARIFA_LINHAQUATRO_VOLTA,
    OPERADORA_IDA,
    OPERADORA_VOLTA,
    3,  -- Março
    2025
FROM FUNCIONARIO 
WHERE AUDITORIA_ID = 1 
  AND (MES_REFERENCIA IS NULL OR MES_REFERENCIA != 3)
LIMIT 10;

-- Para inserir mais meses, copie e altere o MES_REFERENCIA (4-12) e ajuste os multiplicadores

-- Verificar dados inseridos:
-- SELECT MES_REFERENCIA, ANO_REFERENCIA, COUNT(*) as total_funcionarios
-- FROM FUNCIONARIO 
-- WHERE AUDITORIA_ID = 1
-- GROUP BY MES_REFERENCIA, ANO_REFERENCIA
-- ORDER BY ANO_REFERENCIA, MES_REFERENCIA;

